const item= [
    {
      id:'149',
        image:'images/bag.jpg',
        company:'FLYING BERRY',
        item_name:'FLYING BERRY Womens Handbags',
        original_price:1895,
        current_price:5500,
        discount_percentage:66,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.3,
            count:556,
        },
    },
    {
      id:'150',
        image:'images/bag2.jpg',
        company:'EXOTIC BAG',
        item_name:'EXOTIC hand bag for women',
        original_price:1327,
        current_price:3299,
        discount_percentage:60,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.1,
            count:2256,
        },
    },{
      id:'151',
        image:'images/bag3.jpg',
        company:'EXOTIC SLING BAG',
        item_name:'EXOTIC Color block Sling Bag for Girls/Women',
        original_price:999,
        current_price:2599,
        discount_percentage:62,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.1,
            count:556,
        },
    },{
      id:'152',
        image:'images/bag4.jpg',
        company:'SACCI MUCCI',
        item_name:'SACCI MUCCI Sling Crossbody Bag for Girls and Women Made with Durable Vegan',
        original_price:629,
        current_price:1499,
        discount_percentage:58,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.8,
            count:556,
        },
    },{
      id:'153',
        image:'images/bag5.jpg',
        company:'LYROVO',
        item_name:'Lyrovo Women Sling Cross-body Handbag',
        original_price:899,
        current_price:1999,
        discount_percentage:55,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.2,
            count:1227,
        },
    },{
      id:'154',
        image:'images/bag6.jpg',
        company:'Sling Cross',
        item_name:'Lyrovo Women Sling Cross-body Handbag',
        original_price:849,
        current_price:1999,
        discount_percentage:58,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.7,
            count:987,
        },
    },{
      id:'155',
        image:'images/bag7.jpg',
        company:'EXOTIC VIBRANT',
        item_name:'Sling/Shoulder Bag for Womens & Girls',
        original_price:700,
        current_price:2499,
        discount_percentage:68,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.2,
            count:1256,
        },
    },{
      id:'156',
        image:'images/bag8.jpg',
        company:'DIXON Canvas',
        item_name:' Fabric Casual Design Trendy Shoulder Handheld Side Tote Handbag For Women',
        original_price:399,
        current_price:1299,
        discount_percentage:69,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.8,
            count:111,
        },
    },
]