const item= [
    {
      id:'157',
        image:'images/sheet1.jpg',
        company:'IRA HOME 350TC',
        item_name:'Bamboo Bed Sheet Set 4-Piece Luxury Bedding in Romantic Dark Pink ',
        original_price:3699,
        current_price:7999,
        discount_percentage:54,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:5.0,
            count:12,
        },
    },
     {
      id:'158',
        image:'images/sheet2.jpg',
        company:'DECOMIZER XXL',
        item_name:'Microfiber Soft Cotton Super King Size Bedsheet for Double Bed, ',
        original_price:849,
        current_price:1999,
        discount_percentage:58,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:42,
        },
    }, {
      id:'159',
        image:'images/sheet3.jpg',
        company:'DECOMIZER XXL',
        item_name:'Microfiber Soft Cotton Super King Size Bedsheet for Double Bed, ',
        original_price:749,
        current_price:1999,
        discount_percentage:63,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.9,
            count:730,
        },
    }, {
      id:'160',
        image:'images/sheet4.jpg',
        company:'LOOMLYFE',
        item_name:'Cotton Super King Size Bedsheet for Double Bed',
        original_price:836,
        current_price:1999,
        discount_percentage:58,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:1469,
        },
    }, {
      id:'161',
        image:'images/sheet5.jpg',
        company:'HUESLAND',
        item_name:'Ahmedabad Cotton 144 TC Cotton King Size',
        original_price:899,
        current_price:1995,
        discount_percentage:55,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:5480,
        },
    }, {
      id:'162',
        image:'images/sheet6.jpg',
        company:'IRA HOME 350TC',
        item_name:'Collection Super King Size Bedsheets with 2 King Size Pillow Co',
        original_price:549,
        current_price:1499,
        discount_percentage:63,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.8,
            count:2505,
        },
    }, {
      id:'163',
        image:'images/sheet7.jpg',
        company:'STORY@HOME',
        item_name:' Bedsheet for King Size Bed |',
        original_price:1249,
        current_price:3999,
        discount_percentage:69,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:1641,
        },
    }, {
      id:'164',
        image:'images/sheet8.jpg',
        company:'BSB HOME',
        item_name:'Cotton 4 Pcs Bedding Set for King Size Double Bed (78x72 Inches)  1',
        original_price:599,
        current_price:1999,
        discount_percentage:70,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:5.0,
            count:1542,
        },
    },
]