const item= [
    {
      id:'101',
        image:'images/cetaphil.jpg',
        company:'Galderma',
        item_name:'Cetaphil Gentle Skin Cleanser,125ml',
        original_price:769,
        current_price:667,
        discount_percentage:13,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.2,
            count:12566,
        },
    },
    {
        id:'102',
        image:'images/dot.jpg',
        company:'Dot & Key',
        item_name:'Dot & Key CICA Face Wash for Acne Prone Skin, 2% Salicylic Acid with Green Tea',
        original_price:129,
        current_price:249,
        discount_percentage:20,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.6,
            count:12566,
        },
    },
    {
        id: '103',
        image: 'images/vellabita.webp',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id:'104',
        image:'images/primer.jpg',
        company:'LAKME',
        item_name:'LAKMÉ 9 To 5 Primer With Matte Powder Medium Coverage All Skin Foundation Compact, Silky Golden, 9G',
        original_price:259,
        current_price:575,
        discount_percentage:55,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.2,
            count:12566,
        },
    },
    { id:'105',
        image:'images/pears.jpg',
        company:'Pears',
        item_name:'Pears Pure & Gentle Shower Gel SuperSaver XL Pump Bottle With 98% Pure Glycerine',
        original_price:249,
        current_price:425,
        discount_percentage:42,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.6,
            count:12566,
        },
    },
    {
       id:'106',
        image:'images/lipstick.jpg',
        company:'MARS',
        item_name:'MARS Creamy Matte Long Lasting Lipstick for Women | Creamy Lipstick Light Weight (3.2 gm) (02-Zesty Zumba)',
        original_price:179,
        current_price:199,
        discount_percentage:10,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:12566,
        },
    },
    {
        id:'107',
        image:'images/eyeshadowp.jpg',
        company:'LAKME',
        item_name:'LAKMÉ Ultimteglam Shimmery Eyeshadow Sunkissed Powder, 11.7G, Assorted',
        original_price:410,
        current_price:425,
        discount_percentage:4,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:12566,
        },
    },
    {
         id: '108',
        image: 'images/earing.jpg',
        company: 'DEW MAT',
        item_name: 'meenakari oxidised kundans flower Temple South Indian Traditional Ear rings Set stylish Big Jhumki Combo pack of 6.',
        original_price:229,
        current_price: 699,
        discount_percentage:75,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        rating: {
            stars: 5.0,
            count: 1400,
        },
    }
];
    