const item= [
    {
      id:'117',
        image:'images/foot.jpg',
        company:'AGARO Callus',
        item_name:'Remover with 3 Interchangeable Head Rollers, Electronic Foot Scrubber For Callus & Dead Skin Removal, Pedicure Device, 2 Speed, Rechargeable Foot Care, Waterproof, CR1727, Pink',
        original_price:896,
        current_price:1299,
        discount_percentage:31,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.20,
            count:12886,
        },
    },
    {
      id:'118',
        image:'images/press.jpg',
        company:'PHILIPS',
        item_name:'PHILIPS Stainless_Steel Heavyweight Dry Iron Gc181/8-1000 Watts Power, Black Non-Stick Soleplate, Ergonomic Grip',
        original_price:1349,
        current_price:1499,
        discount_percentage:10,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.2,
            count:25257,
        },
    },
    {
      id:'119',
        image:'images/clock.jpg',
        company:'CBK Digital',
        item_name:'CBK Digital Alarm Wall Clock Table Clock, 9 inch LED Clock with Date and Temperature,Auto Dimming, Day of Week, Remote Control, Perfect for Home Office Table Desk, Living Room',
        original_price:1699,
        current_price:3999,
        discount_percentage:58,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.1,
            count:1235,
        },
    },
    {
      id:'120',
        image:'images/mixture.jpg',
        company:'ATOMBERG YULIA',
        item_name:'Samsung 183 L, 4 Star, Digital Inverter, Direct-Cool Single Door Refrigerator (RR20C1824CR/HL, Red, Camellia Purple, Base Stand Drawer)',
        original_price:11999,
        current_price:6799,
        discount_percentage:43,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.5,
            count:1515,
        },
    },
     {
      id:'121',
        image:'images/ac.jpg',
        company:'Daikin',
        item_name:'Daikin 0.8 Ton 3 Star, Fixed Speed Split AC (Copper, PM 2.5 Filter, 2022 Model, FTL28U, White)',
        original_price:26490,
        current_price:37400,
        discount_percentage:29,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.6,
            count:1876,
        },
    },
     {
      id:'122',
        image:'images/fan.jpg',
        company:'LONGWAY',
        item_name:'LONGWAY Kiger P1 1200 mm/48 inch Ultra High Speed 3 Blade Anti-Dust Decorative Star Rated Ceiling Fan (Smoked Brown, Pack of 1)',
        original_price:1989,
        current_price:9945,
        discount_percentage:10,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:1395,
        },
    },
    {
      id:'123',
        image:'images/light.jpg',
        company:'ELEPHANTBOAT',
        item_name:' Table Lamp for Study Room, 4 in 1 Rechargeable Desk Lamp Light for Study with Powerful Magnets Portable USB Table',
        original_price:1483,
        current_price:2249,
        discount_percentage:34,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:5.0,
            count:1395,
        },
    },
     {
      id:'124',
        image:'images/cooler.jpg',
        company:'MORTON DAVIES',
        item_name:'  Mini Cooler for Room Cooling AC Portable Mini Fan Cooler with 7 Colors LED Light, 1/2/3 H Timer, 3 Wind Speeds and 3 Spray Modes for Office,Home,Travel',
        original_price:599,
        current_price:999,
        discount_percentage:40,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:1395,
        },
    },
    
]