const item= [
    {
      id:'125',
        image:'images/shortt.jpg',
        company:'FRECIILOOKS',
        item_name:' Mens Regular Fit Low Rise Cargos Trousers | Baggy Cargo Pants for Man | ',
        original_price:699,
        current_price:1999,
        discount_percentage:65,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.1,
            count:192,
        },
    },
    {
      id:'126',
        image:'images/mmshirt.jpg',
        company:'GRECIILOOKS',
        item_name:' MenS Formal Button Down Shirt – Slim Fit Office Wear Shirts for Men | Textured Long Sleeve Cotton Blend |',
        original_price:529,
        current_price:1999,
        discount_percentage:74,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:2480,
        },
    },
    {
      id:'127',
        image:'images/mshirt.jpg',
        company:'Zans & Mens',
        item_name:'Zans & Mens Premium Linen Casual Full Sleeve Shirt for Man',
        original_price:495,
        current_price:1999,
        discount_percentage:75,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.3,
            count:2480,
        },
    },
     {
      id:'128',
        image:'images/jeeans.jpg',
        company:'Max URB_N',
        item_name:'Max URB_N Men Regular Fit Solid Resort Shirt',
        original_price:899,
        current_price:999,
        discount_percentage:10,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.9,
            count:2480,
        },
    },
    {
      id:'129',
        image:'images/jean.jpg',
        company:'Raymond',
        item_name:'Raymond Mens Mid Rise Slim Fit Checks Pattern Poly Viscose Blend Flat Front Formal Trouser',
        original_price:1149,
        current_price:2299,
        discount_percentage:50,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:2480,
        },
    },
    
    {
      id:'130',
        image:'images/shitt.jpg',
        company:'Symbol Premium',
        item_name:'Symbol Premium Mens Casual Cotton Poplin Shirt (Regular Fit)',
        original_price:1049,
        current_price:2409,
        discount_percentage:58,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:2480,
        },
    },
        {
      id:'131',
        image:'images/tshirt.jpg',
        company:'Lymio Polo',
        item_name:'Lymio Polo T Shirt for Men || Men Casual T-Shirt || Available in Combo Packs (Polo 44 to 47)',
        original_price:449,
        current_price:2999,
        discount_percentage:85,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.8,
            count:2480,
        },
    },
   
    {
          id:'132',
        image:'images/hoody.jpg',
        company:'Imsa Moda',
        item_name:'Imsa Moda Stylish Hoodies/Sweatshirt Polycotton Hoodies for Running, Gym Warm Travel Hoodies for Men',
        original_price:449,
        current_price:999,
        discount_percentage:50,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.5,
            count:2480,
    }
},
]