const item= [
    {
      id:'133',
        image:'images/shoes.jpg',
        company:'Bacca Bucci',
        item_name:'Bacca Bucci Men Lace Up Sneaker Shoes',
        original_price:1199,
        current_price:2499,
        discount_percentage:52,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.7,
            count:1986,
        },
    },
    {
      id:'134',
        image:'images/nike.jpg',
        company:'Nike',
        item_name:'Nike Men Lace Up Basketball Shoe',
        original_price:5889,
        current_price:7095,
        discount_percentage:17,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.6,
            count:1986,
        },
    },
     {
      id:'135',
        image:'images/shooe.jpg',
        company:'CULTSPORT',
        item_name:'Mens Windblazer Running Shoes, Engineered Upper Mesh, Breathable, German',
        original_price:1999,
        current_price:4999,
        discount_percentage:60,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.9,
            count:1786,
        },
    },
    {
      id:'136',
        image:'images/shoooe.jpg',
        company:'ATHCO',
        item_name:'ATHCO Mens Akron Memory Foam Comfort Shoes|Running|Walking|Training|',
        original_price:699,
        current_price:2999,
        discount_percentage:77,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.9,
            count:1286,
        },
    },
    {
      id:'137',
        image:'images/Shoe.jpg',
        company:'BRUTON EVA',
        item_name:'BRUTON EVA Lite Sport Shoes Running Shoes',
        original_price:492,
        current_price:2999,
        discount_percentage:84,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.9,
            count:12886,
        },
    },
     {
      id:'138',
        image:'images/Shooes.jpg',
        company:'EVANID',
        item_name:'Birde Comfortable Lightwight Sports Walking Shoes for Men',
        original_price:799,
        current_price:2999,
        discount_percentage:71,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.0,
            count:186,
        },
    },
      {
      id:'139',
        image:'images/bshooe.jpg',
        company:'Sneakers',
        item_name:'Skechers Men Summits Brisbane Sneakers',
        original_price:2740,
        current_price:4299,
        discount_percentage:36,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.1,
            count:1025,
        },
    },
    {
      id:'140',
        image:'images/blshooe.jpg',
        company:'ASICS',
        item_name:'ASICS Mens Versablast 4 Sports Shoes',
        original_price:6999,
        current_price:4999,
        discount_percentage:10,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.4,
            count:1025,
        },
    },
]