const item= [
    {
      id:'109',
        image:'images/panda.jpg',
        company:'Storscent',
        item_name:'Storescent Cute Panda Plush with Bamboo, Kawaii Soft Panda in Bamboo Stuffed Animals Toy, Plushies Doll Gifts for Kids Girls Boys Birthday Valentine (Panda in Bamboo)l',
        original_price:398,
        current_price:999,
        discount_percentage:60,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.2,
            count:12886,
        },
    },
    {
    id:'110',
        image:'images/storio.jpg',
        company:'Storio',
        item_name:'Storio Toy Plushie Super Soft Toys for Kids | Adorable Plush Soft Toys for Baby Boys and Girls Kids - Penguine Black & White',
        original_price:189,
        current_price:399,
        discount_percentage:39,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:5.2,
            count:12069,
        },
    },
    {
    id:'111',
        image:'images/dog.jpg',
        company:'Storio',
        item_name:'Babique Dog Sitting Plush Soft Toy Cute Kids Animal Home Decor Boys/Girls White (25 cm)',
        original_price:299,
        current_price:209,
        discount_percentage:10,
        return_period:7,
        delivery_date:'21 oct 2025',
        rating:{
            stars:4.3,
            count:12334,
        },
    },
    {
    id:'112',
        image:'images/penguin.jpg',
        company:'Niku',
        item_name: 'Penguin (Pink, 25cm) |Stuffed Soft Toy Teddy Bear for Girls, Boys and Kids, Safe, Return Birthday Gift for Girls Valentines',
        original_price:326,
        current_price:399,
        discount_percentage:18,
        return_period:7,
        delivery_date:'21 oct 2025',
        rating:{
            stars:4.1,
            count:14564,
        },
    },
     {
    id:'113',
        image:'images/bear.jpg',
        company:'Niku',
        item_name: 'Niku Breathing Teddy Bear Otter Soft Toys for Kids Baby Girls Grey Colour | Glowing Music for Baby Sensory Sleep | Lights Rhythmic Simulation Plush with Soothing Sound | Best Birthday Gift',
        original_price:326,
        current_price:399,
        discount_percentage:18,
        return_period:7,
        delivery_date:'21 oct 2025',
        rating:{
            stars:4.7,
            count:12596,
        },
    },
      {
    id:'114',
        image:'images/teddy.jpg',
        company:'HUGN',
        item_name: 'HUG FEEL SOFT TOYS Pihu Enterprises Plush Cuddle Teddy Bear Plush & Stuffed Toys (Cream, 4 ft',
        original_price:1099,
        current_price:1999,
        discount_percentage:45,
        return_period:7,
        delivery_date:'21 oct 2025',
        rating:{
            stars:5.3,
            count:1357,
        },
    },
     {
    id:'115',
        image:'images/kitty.jpg',
        company:'AVSHUB',
        item_name: 'AVSHUB Soft Toys Kitti for Kids Animal Cute Lovely Cartoon Lovable Huggable Birthday Gift Babies for New Born, Girls, Boy, Home Decor (White Pink) 11Buy24-Kitti-20cm',
        original_price:399,
        current_price:699,
        discount_percentage:43,
        return_period:7,
        delivery_date:'21 oct 2025',
        rating:{
            stars:4.1,
            count:11566,
        },
    },
    {
    id:'116',
        image:'images/tinytoy.jpg',
        company:'TINYTOTEM',
        item_name: 'Tinytotem Stitch Soft Toy for Kids Teddy Bear Gift for Baby Girl Plush Toys Babies Cuddly Animal Stuffed Gifts for Girls Toddlers Boys & Girls Hoodie',
        original_price:699,
        current_price:999,
        discount_percentage:65,
        return_period:7,
        delivery_date:'21 oct 2025',
        rating:{
            stars:3.7,
            count:12546,
        },
    },
]