const item= [
    {
      id:'141',
        image:'images/women.jpg',
        company:'Storscent',
        item_name:'Amazon Brand - Myx Womens Cotton Printed A-line Short Kurti',
        original_price:449,
        current_price:699,
        discount_percentage:36,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.6,
            count:6416,
        },
    },
    {
      id:'142',
        image:'images/wtshirt.jpg',
        company:'TOPLOT',
        item_name:'TOPLOT Tops for Women || Western Tops for Woman Stylish || Crop t-Shirt Western Pack of 2 (5258 00-02)',
        original_price:399,
        current_price:1599,
        discount_percentage:75,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.6,
            count:7316,
        },
    },
     {
      id:'143',
        image:'images/skrit.jpg',
        company:'VAGISHA',
        item_name:'VAGISHA Long Skirts for Women Traditional Ethnic Jaipuri Skirt|American Poly Spandex Casual Skirt for Girls|Summer Skirt|Huge Flare 39Inch Height (No Top Included)',
        original_price:499,
        current_price:2999,
        discount_percentage:78,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.6,
            count:4226,
        },
    },
    {
      id:'144',
        image:'images/jeans.jpg',
        company:'Leriya ',
        item_name:'Leriya Fashion Summer Dress for Women ',
        original_price:429,
        current_price:1999,
        discount_percentage:79,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.1,
            count:7416,
        },
    },
    {
      id:'145',
        image:'images/wjeans.jpg',
        company:'KOTTY ',
        item_name:'KOTTY Straight Womens Jeans ',
        original_price:477,
        current_price:1999,
        discount_percentage:76,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:3.5,
            count:416,
        },
    },
    {
      id:'146',
        image:'images/suit.jpg',
        company:'SS MART ',
        item_name:'SS MART Women Cotton Embroidered Straight Kurta & Pant with Dupatta Set (Purple)',
        original_price:1499,
        current_price:1999,
        discount_percentage:25,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.6,
            count:5416,
        },
    },
    {
      id:'147',
        image:'images/suitt.jpg',
        company:'MYX-NSK ',
        item_name:'Womens Blend Regular Embroidered',
        original_price:1849,
        current_price:3199,
        discount_percentage:42,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.0,
            count:5416,
        },
    },
     {
      id:'148',
        image:'images/wtshirtt.jpg',
        company:'LIBOZA ',
        item_name:'Kurti for Women - Short',
        original_price:474,
        current_price:2399,
        discount_percentage:80,
        return_period:7,
        delivery_date:'10 oct 2025',
        rating:{
            stars:4.9,
            count:546,
        },
    },
]